/*
https://github.com/golang/go/blob/master/src/cmd/go/main.go#L1-L9
https://github.com/makenowjust/quine/blob/main/quine.go#L4-L7
https://github.com/munvoseli/bqcwigo/blob/trunk/hello.go#L1062-L1063
https://github.com/Bright-Kunakorn/concurrent-programming/blob/main/area.go#L16
https://github.com/aws/amazon-ssm-agent/blob/mainline/agent/times/times.go#L61
https://github.com/golang/tools/blob/master/internal/diff/myers/diff.go#L195-L198
https://github.com/diptangsu/Sorting-Algorithms/blob/master/Go/timsort.go#L82
https://github.com/freetsdb/freetsdb/blob/master/pkg/roaring/bitmapcontainer.go#L974
https://github.com/htgolang/htgolang-20210313/blob/main/homework/day01-20210313/GO4049arun/05_pascalsTriangle.go#L18
https://github.com/FurkanSamaraz/IPFS-Github-Storage/blob/main/main.go#L28-L29
https://github.com/gomodule/redigo/blob/master/redis/conn.go#L441
https://github.com/golang/go/blob/master/src/runtime/proc.go#L5673C2-L5675
https://github.com/goplus/gop/blob/main/parser/parser.go#L240
https://github.com/gomodule/redigo/blob/master/redis/conn.go#L441
https://github.com/golang/go/blob/master/src/math/sincos.go#L47
https://github.com/pscoro/perpetuan/blob/master/db.go#L58
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/queue/scheduling_queue.go#L1181
https://github.com/dnuffer/dpcode/blob/master/gcd_euclid/go/solution.go#L18-L20
https://github.com/golang/go/blob/master/src/math/sincos.go#L47
https://github.com/Rosettea/Hilbish/blob/master/readline/completers/patterns.go#L507
https://github.com/golang/go/blob/master/src/fmt/doc.go#L164
https://github.com/pscoro/perpetuan/blob/master/db.go#L58
https://github.com/LyricLy/jan-Insi/blob/master/file.go#L1-L25
*/
